[build]
src = "source"
obj = "target/build"
out = "target"
bip = "3.0+"

[build.c]
std = "c11"
include = [ "include" ]
hide-symbols = true

[build.cpp]
std = "c++23"
include = [ "include" ]
hide-symbols = true

[driver]
exe = "vm-prototype"
lang = "cpp"
libs = [ "nwge", "SDL2" ]
